[build]
builder = "RAILPACK"

[deploy]
preDeployCommand = "python manage.py migrate && python manage.py collectstatic --noinput"
startCommand = "gunicorn connecthub_project.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"