# Generated by Django 5.2.8 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_comment_id_alter_post_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
