# Generated by Django 5.2.8 on 2026-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_comment_id_alter_post_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Wide banner image shown at the top of your profile', null=True, upload_to='cover_photos/'),
        ),
    ]
