# Generated by Django 5.2.8 on 2026-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_pics/default_cover_avatar.png', null=True, upload_to='cover_pics/'),
        ),
    ]
